server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: dnsforwarder
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 10s
    relabel_configs:
      # Only keep containers labeled logging=promtail
      - source_labels: [__meta_docker_container_label_logging]
        regex: promtail
        action: keep
      # Set job label in Loki
      - source_labels: [__meta_docker_container_name]
        target_label: container_name

