global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: 'dns-forwarder'
   static_configs:
    - targets: ['DNS-FORWARDER-SERVICE-IP-CHANGE-ME:8080']
   metrics_path: '/metrics'
   scrape_interval: 30s
